---
- name: restart harbor
  docker_service:
    project_src: "{{ harbor_install_dir }}/harbor"
    files: "{{ harbor_docker_compose_files }}"
    state: present
    restarted: true

- name: start harbor
  docker_service:
    project_src: "{{ harbor_install_dir }}/harbor"
    files: "{{ harbor_docker_compose_files }}"
    state: present

- name: stop harbor
  docker_service:
    project_src: "{{ harbor_install_dir }}/harbor"
    files: "{{ harbor_docker_compose_files }}"
    state: absent
